### ISSUE TITLE
Proxyman cannot handle HTTPS traffic whose CONNECT request HOST is IP instead of server name.

### ISSUE THREAD

**Issue by cesaryuan** [ProxymanApp/proxyman-windows-linux#288]
## Description

Hi, thanks for you excellant product!

I'm trying to capture traffic from Android application. Here is my procedures:

1. Root the android device
2. install the proxyman cert to system CA
3. install Proxydroid app to phone
4. set Proxydroid to transfer the traffic to [ProxymanIp]:9090
5. open android chrome and then check capture on Proxyman

![image](https://github.com/ProxymanApp/Proxyman/assets/35998162/7dcdcf51-7dd0-45be-8927-958bbd0b62cf)

We can see that all HTTPS capture cannot get domain but only ip. It causes that proxyman cannot capture HTTPS correctly.

However, other alternative proxy software on Windows such as Fiddler Classic and Mitmproxy can handle this correctly (Fiddler need additional settings). As far as I know, they obtain the server name indicator from the client's TLS handshake instead of using the HOST field from the CONNECT. (Reference [https://groups.google.com/g/httpfiddler/c/hvsDR14j1Lg/m/P02zBzIYCE4J](https://groups.google.com/g/httpfiddler/c/hvsDR14j1Lg/m/P02zBzIYCE4J))

It seems there is an similar issue. But I'm not sure. [Proxyman does not use SNI when generating certificates for use with SSL Proxying · Issue #1581 · ProxymanApp/Proxyman](https://github.com/ProxymanApp/Proxyman/issues/1581)

Therefore, it will be wonderful if you can fix this issue.

## Steps to Reproduce

1. Root the android device
2. install the Proxyman cert to android system CA
3. install Proxydroid app to phone
4. set Proxydroid to transfer the traffic to <Proxyman's IP>:9090
5. open android chrome and then check capture on Proxyman

## Current Behavior

![image](https://github.com/ProxymanApp/Proxyman/assets/35998162/503f918b-36fd-48ef-8d06-70b6ddb8c172)

## Expected Behavior

![image](https://github.com/ProxymanApp/Proxyman/assets/35998162/999fc8a9-a49e-4019-8769-145af18fbf61)

## Environment

- App version: Proxyman Windows 2.2.0
- Windows version: 22H2

**Comment by NghiaTranUIT** [comment]
Thanks @cesaryuan for the detailed feedback. Our team is going to fix it asap 👍

**Comment by NghiaTranUIT** [comment]
@cesaryuan I've confirmed that we can reproduce the bug with Android Emulator too. Gonn fix it now.

**Comment by cesaryuan** [comment]
> @cesaryuan I've confirmed that we can reproduce the bug with Android Emulator too. Gonna fix it now.

Thank you for your quick response! 😘

**Comment by NghiaTranUIT** [comment]
@cesaryuan can you try to Disable the Private DNS in Android Settings -> Network & internet -> Advanced -> Private DNS

From what I know, it can fix the bug.

Ref: https://stackoverflow.com/questions/68819088/fiddler-ip-address-being-captured-instead-of-url-from-android-emulator

**Comment by cesaryuan** [comment]
> @cesaryuan can you try to Disable the Private DNS in Android Settings -> Network & internet -> Advanced -> Private DNS
> 
> From what I know, it can fix the bug.
> 
> Ref: https://stackoverflow.com/questions/68819088/fiddler-ip-address-being-captured-instead-of-url-from-android-emulator

Thanks! I checked that this option has been disabled already. 
![image](https://github.com/ProxymanApp/proxyman-windows-linux/assets/35998162/2bdae40b-db64-4418-abfd-7dd0b34d054e)

**Comment by cesaryuan** [comment]
Hi, is there any progress on it?

**Comment by kics223w1** [comment]
Hi, this bug will continue to be fixed after we finish updating [new UI for Proxyman Windows](https://github.com/ProxymanApp/proxyman-windows-linux/issues/305). For now, I haven't found a solution or workaround for this.

**Comment by cesaryuan** [comment]
Hi, is there any progress on it?

**Comment by NghiaTranUIT** [comment]
@kics223w1 can you share the progress? I guess we should try to reproduce this issue again on the latest build. Maybe it's already fixed

**Comment by kics223w1** [comment]
I think so, I'll reproduce this issue on version 2.15.0 and if it's not fixed, I'll fix this 👍🏻

**Comment by kics223w1** [comment]
Hi @cesaryuan , this issue is fixed on version 2.15.0

**Comment by cesaryuan** [comment]
> this issue is fixed on version 2.15.0

Hello, I tried it on my own computer and found that there is still a problem

**Comment by kics223w1** [comment]
@cesaryuan 
Can you walk me through how you reproduce this? 
I used the reproduced steps in the pull request and I can see the hostname perfectly
